"""Render a standalone single-file Python install script from an InstallConfig."""

from __future__ import annotations

import re
from pathlib import Path

from artix_dev.config import InstallConfig


_SRC_DIR = Path(__file__).parent


def _read_module(name: str) -> str:
    """Read a module's source and strip inter-package imports and docstrings."""
    source = (_SRC_DIR / name).read_text()

    # Remove module docstring (first triple-quoted string)
    source = re.sub(r'^""".*?"""\n*', "", source, count=1, flags=re.DOTALL)

    # Remove 'from __future__ import annotations'
    source = re.sub(r"^from __future__ import annotations\n*", "", source, flags=re.MULTILINE)

    # Remove multi-line imports: from ... import (\n...\n)
    source = re.sub(
        r"^(from|import) [^\n]*\(.*?\)\n*",
        "", source, flags=re.MULTILINE | re.DOTALL,
    )
    # Remove single-line imports
    source = re.sub(r"^(from|import) .+\n*", "", source, flags=re.MULTILINE)

    return source.strip()


def render_phase1(cfg: InstallConfig) -> str:
    """Generate a self-contained Python script for Phase 1 installation."""
    errors = cfg.validate()
    if errors:
        raise ValueError("Config validation failed:\n" + "\n".join(errors))

    toml_config = cfg.to_toml()

    config_src = _read_module("config.py")
    run_src = _read_module("run.py")
    phase1_src = _read_module("phase1.py")

    return f'''\
#!/usr/bin/env python3
# Artix Linux Phase 1 installer — generated by artix-dev
# Hostname: {cfg.system.hostname}
# Disk: {cfg.disk.device} ({cfg.disk.disk_type.value})
# Kernel: {cfg.kernel_package}

from __future__ import annotations

import os
import subprocess
import sys
import tomllib
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path


# === config.py ===

{config_src}


# === run.py ===

{run_src}


# === phase1.py ===

{phase1_src}


# === Main ===

_TOML_CONFIG = """\\
{toml_config}"""

if __name__ == "__main__":
    cfg = InstallConfig.from_toml(_TOML_CONFIG)
    run_phase1(cfg)
'''
