"""Render a standalone bash install script from an InstallConfig."""

from __future__ import annotations

import shlex

from artix_dev.config import InstallConfig, OptionalService, SshPolicy
from artix_dev.phase1 import OPTIONAL_SERVICE_NAMES, OPTIONAL_SERVICE_PACKAGES


def render_phase1(cfg: InstallConfig) -> str:
    """Generate a self-contained bash script for Phase 1 installation."""
    errors = cfg.validate()
    if errors:
        raise ValueError("Config validation failed:\n" + "\n".join(errors))

    lines: list[str] = []

    def emit(line: str = "") -> None:
        lines.append(line)

    def heading(msg: str) -> None:
        emit()
        emit(f'echo "============================================================"')
        emit(f'echo "  {msg}"')
        emit(f'echo "============================================================"')
        emit()

    def _quote(arg: str) -> str:
        """Quote a bash argument, but pass through variable references."""
        if "$" in arg:
            return arg
        return shlex.quote(arg)

    def cmd(*args: str) -> None:
        emit(" ".join(_quote(a) for a in args))

    def shell(script: str) -> None:
        emit(script)

    def chroot(*args: str) -> None:
        emit("artix-chroot /mnt " + " ".join(_quote(a) for a in args))

    def chroot_shell(script: str) -> None:
        emit(f"artix-chroot /mnt /bin/bash -c {shlex.quote(script)}")

    def write_file(path: str, content: str) -> None:
        emit(f"cat > {_quote(path)} <<'ARTIX_EOF'")
        emit(content.rstrip("\n"))
        emit("ARTIX_EOF")

    def append_file(path: str, content: str) -> None:
        emit(f"cat >> {_quote(path)} <<'ARTIX_EOF'")
        emit(content.rstrip("\n"))
        emit("ARTIX_EOF")

    # --- Header ---
    emit("#!/bin/bash")
    emit("# Artix Linux Phase 1 installer — generated by artix-dev")
    emit(f"# Hostname: {cfg.system.hostname}")
    emit(f"# Disk: {cfg.disk.device} ({cfg.disk.disk_type.value})")
    emit(f"# Kernel: {cfg.kernel_package}")
    emit("set -euo pipefail")
    emit()
    emit("if [[ $EUID -ne 0 ]]; then")
    emit('    echo "FATAL: This script must be run as root"')
    emit("    exit 1")
    emit("fi")

    # --- Variables ---
    emit()
    emit("# Configuration")
    emit(f"DISK={shlex.quote(cfg.disk.device)}")
    emit(f"PART={shlex.quote(cfg.disk.part_prefix)}")
    emit(f"ESP_SIZE={shlex.quote(cfg.disk.esp_size)}")
    emit(f"KERNEL={shlex.quote(cfg.kernel_package)}")
    emit(f"HEADERS={shlex.quote(cfg.kernel_headers_package)}")
    emit(f"HOSTNAME={shlex.quote(cfg.system.hostname)}")
    emit(f"LOCALE={shlex.quote(cfg.system.locale)}")
    emit(f"TIMEZONE={shlex.quote(cfg.system.timezone)}")
    emit(f"USERNAME={shlex.quote(cfg.system.username)}")
    emit(f"BOOT_SIZE={shlex.quote(cfg.lvm.boot_size)}")
    emit(f"SWAP_SIZE={shlex.quote(cfg.lvm.swap_size)}")
    emit(f"TMPFS_SIZE={shlex.quote(cfg.system.tmpfs_size)}")
    emit(f"GRUB_TIMEOUT_VAL={cfg.grub.timeout}")
    emit(f"GRUB_GFXMODE_VAL={shlex.quote(cfg.grub.gfxmode)}")

    # --- Install live deps ---
    heading("Installing live environment dependencies")
    cmd("pacman", "-Sy", "--noconfirm",
        "gptfdisk", "parted", "cryptsetup", "lvm2", "dosfstools")

    # --- Partition disk ---
    heading("Partitioning disk")
    cmd("sgdisk", "--zap-all", "${DISK}")
    if cfg.disk.trim:
        cmd("blkdiscard", "${DISK}")
    cmd("parted", "-s", "${DISK}", "mklabel", "gpt")
    cmd("parted", "-s", "-a", "optimal", "${DISK}",
        "mkpart", "ESP", "fat32", "0%", "${ESP_SIZE}")
    cmd("parted", "-s", "${DISK}", "set", "1", "esp", "on")
    cmd("parted", "-s", "-a", "optimal", "${DISK}",
        "mkpart", "LUKS", "ext4", "${ESP_SIZE}", "100%")
    cmd("parted", "-s", "${DISK}", "set", "2", "lvm", "on")
    cmd("parted", "-s", "${DISK}", "print")

    # --- LUKS ---
    heading("Setting up LUKS encryption")
    cmd("cryptsetup", "benchmark")
    cmd("cryptsetup",
        "--verbose",
        "--type", cfg.luks.luks_type,
        "--cipher", cfg.luks.cipher,
        "--key-size", str(cfg.luks.key_size),
        "--hash", cfg.luks.hash,
        "--iter-time", str(cfg.luks.iter_time),
        "--use-random",
        "--verify-passphrase",
        "luksFormat", "${PART}2")
    cmd("cryptsetup", "luksOpen", "${PART}2", "lvm-system")

    # --- LVM ---
    heading("Setting up LVM")
    cmd("pvcreate", "/dev/mapper/lvm-system")
    cmd("vgcreate", "lvmSystem", "/dev/mapper/lvm-system")
    cmd("lvcreate", "--contiguous", "y", "--size", "${BOOT_SIZE}",
        "lvmSystem", "--name", "volBoot")
    cmd("lvcreate", "--contiguous", "y", "--size", "${SWAP_SIZE}",
        "lvmSystem", "--name", "volSwap")
    cmd("lvcreate", "--contiguous", "y", "--extents", "+100%FREE",
        "lvmSystem", "--name", "volRoot")

    # --- Format ---
    heading("Formatting partitions")
    cmd("mkfs.fat", "-F32", "-n", "ESP", "${PART}1")
    cmd("mkfs.ext4", "-L", "BOOT", "/dev/lvmSystem/volBoot")
    cmd("mkswap", "-L", "SWAP", "/dev/lvmSystem/volSwap")
    cmd("mkfs.ext4", "-L", "ROOT", "/dev/lvmSystem/volRoot")

    # --- Mount ---
    heading("Mounting partitions")
    cmd("swapon", "/dev/lvmSystem/volSwap")
    cmd("mount", "/dev/lvmSystem/volRoot", "/mnt")
    cmd("mkdir", "-p", "/mnt/boot")
    cmd("mount", "/dev/lvmSystem/volBoot", "/mnt/boot")
    cmd("mkdir", "-p", "/mnt/boot/efi")
    cmd("mount", "${PART}1", "/mnt/boot/efi")

    # --- Base system ---
    heading("Installing base system")
    cmd("basestrap", "/mnt", "base", "base-devel", "dinit", "elogind-dinit")
    cmd("basestrap", "/mnt", "${KERNEL}", "${HEADERS}", "linux-firmware")
    cmd("basestrap", "/mnt",
        "lvm2", "lvm2-dinit", "cryptsetup", "cryptsetup-dinit",
        "device-mapper-dinit")
    cmd("basestrap", "/mnt", "grub", "efibootmgr", "dosfstools")
    cmd("basestrap", "/mnt", "networkmanager", "networkmanager-dinit")
    cmd("basestrap", "/mnt", "openssh", "openssh-dinit")
    cmd("basestrap", "/mnt", "nano", "vi", "less")

    # --- WiFi ---
    heading("Copying WiFi configuration")
    emit("if [[ -d /etc/NetworkManager/system-connections ]] && "
         "ls /etc/NetworkManager/system-connections/* &>/dev/null; then")
    emit("    cp -r /etc/NetworkManager/system-connections /mnt/etc/NetworkManager/")
    emit("else")
    emit('    echo "  No WiFi connections found, skipping."')
    emit("fi")

    # --- fstab ---
    heading("Generating fstab")
    shell("fstabgen -U /mnt >> /mnt/etc/fstab")
    if cfg.disk.trim:
        shell('sed -i "s/relatime/relatime,discard/g" /mnt/etc/fstab')
    append_file("/mnt/etc/fstab",
                f"tmpfs    /tmp    tmpfs    "
                f"rw,nosuid,nodev,relatime,size=${{TMPFS_SIZE}},mode=1777"
                f"    0 0")

    # --- Root password ---
    heading("Setting root password")
    chroot("passwd")

    # --- Keyring ---
    heading("Initializing pacman keyring")
    chroot("pacman", "-Sy", "--noconfirm")
    chroot("pacman-key", "--init")
    chroot("pacman-key", "--populate", "artix")

    # --- Locale ---
    heading("Configuring locale")
    append_file("/mnt/etc/locale.gen", f"${{LOCALE}} UTF-8")
    chroot("locale-gen")
    lang = cfg.system.locale.split()[0] if " " in cfg.system.locale else cfg.system.locale
    write_file("/mnt/etc/locale.conf", f"LANG={lang}")

    # --- Timezone ---
    heading("Configuring timezone")
    chroot("ln", "-sf", "/usr/share/zoneinfo/${TIMEZONE}", "/etc/localtime")
    chroot("hwclock", "--systohc")

    # --- Hostname ---
    heading("Setting hostname")
    write_file("/mnt/etc/hostname", "${HOSTNAME}")

    # --- Caps Lock ---
    if cfg.system.caps_lock_remap:
        heading("Remapping Caps Lock to Control")
        write_file(
            "/mnt/usr/share/kbd/keymaps/personal.map",
            'include "/usr/share/kbd/keymaps/i386/qwerty/us.map.gz"\n'
            "keycode 58 = Control",
        )
        write_file("/mnt/etc/vconsole.conf", "KEYMAP=personal")
        cmd("mkdir", "-p", "/mnt/etc/X11/xorg.conf.d")
        write_file(
            "/mnt/etc/X11/xorg.conf.d/00-keyboard.conf",
            'Section "InputClass"\n'
            '    Identifier "system-keyboard"\n'
            '    MatchIsKeyboard "on"\n'
            '    Option "XkbLayout" "us"\n'
            '    Option "XkbOptions" "ctrl:nocaps"\n'
            "EndSection",
        )

    # --- XON/XOFF ---
    heading("Disabling XON/XOFF flow control")
    append_file("/mnt/etc/profile", "stty -ixon")

    # --- mkinitcpio ---
    heading("Configuring mkinitcpio")
    hooks = (
        "HOOKS=(base udev autodetect microcode modconf block "
        "encrypt keyboard keymap consolefont lvm2 resume filesystems fsck)"
    )
    shell(f"sed -i 's/^HOOKS=.*/{hooks}/' /mnt/etc/mkinitcpio.conf")
    chroot("mkinitcpio", "-p", "${KERNEL}")

    # --- GRUB config ---
    heading("Configuring GRUB")
    discard = ":allow-discards" if cfg.disk.trim else ""
    shell(
        f'LUKS_UUID=$(blkid -s UUID -o value ${{PART}}2)\n'
        f'SWAP_UUID=$(blkid -s UUID -o value /dev/lvmSystem/volSwap)\n'
        f'sed -i "s/^GRUB_CMDLINE_LINUX_DEFAULT=.*/GRUB_CMDLINE_LINUX_DEFAULT='
        f'\\"cryptdevice=UUID=${{LUKS_UUID}}:lvm-system{discard} '
        f'loglevel=3 quiet resume=UUID=${{SWAP_UUID}} net.ifnames=0\\"/" '
        f'/mnt/etc/default/grub'
    )
    append_file("/mnt/etc/default/grub", 'GRUB_ENABLE_CRYPTODISK="y"')
    shell('sed -i \'s/^GRUB_TIMEOUT=.*/GRUB_TIMEOUT="\'${GRUB_TIMEOUT_VAL}\'"/\' '
          '/mnt/etc/default/grub')
    shell('sed -i \'s/^GRUB_TIMEOUT_STYLE=.*/GRUB_TIMEOUT_STYLE="menu"/\' '
          '/mnt/etc/default/grub')
    shell('sed -i \'s/^GRUB_GFXMODE=.*/GRUB_GFXMODE="\'${GRUB_GFXMODE_VAL}\'"/\' '
          '/mnt/etc/default/grub')

    # --- GRUB install ---
    heading("Installing GRUB")
    chroot("grub-install",
           "--target=x86_64-efi",
           "--efi-directory=/boot/efi",
           "--bootloader-id=artix",
           "--recheck")
    chroot("grub-install",
           "--target=x86_64-efi",
           "--efi-directory=/boot/efi",
           "--removable")
    chroot("grub-mkconfig", "-o", "/boot/grub/grub.cfg")

    # --- Base services ---
    heading("Enabling base dinit services")
    base_services = ["lvm2", "NetworkManager", "elogind", "dbus"]
    if cfg.system.ssh != SshPolicy.DISABLE:
        base_services.append("sshd")
    for svc in base_services:
        emit(f"ln -s /etc/dinit.d/{svc} /mnt/etc/dinit.d/boot.d/")

    # --- Optional services ---
    if cfg.optional_services:
        heading("Installing optional services")
        packages: list[str] = []
        for svc in cfg.optional_services:
            packages.extend(OPTIONAL_SERVICE_PACKAGES[svc])
        if packages:
            chroot("pacman", "-S", "--noconfirm", *packages)
        for svc in cfg.optional_services:
            name = OPTIONAL_SERVICE_NAMES[svc]
            emit(f"ln -s /etc/dinit.d/{name} /mnt/etc/dinit.d/boot.d/")

    # --- Extra packages ---
    if cfg.extra_packages:
        heading("Installing extra packages")
        chroot("pacman", "-S", "--noconfirm", *cfg.extra_packages)

    # --- User account ---
    heading(f"Creating user account: {cfg.system.username}")
    chroot("useradd", "-m", "-G", "wheel", "-s", "/bin/bash", "${USERNAME}")
    emit(f'echo "Set password for ${{USERNAME}}:"')
    chroot("passwd", "${USERNAME}")
    shell("sed -i 's/^# *%wheel ALL=(ALL:ALL) ALL/%wheel ALL=(ALL:ALL) ALL/' "
          "/mnt/etc/sudoers")

    # --- SSH ---
    if cfg.system.ssh != SshPolicy.DISABLE:
        heading("Configuring SSH")
        emit("mkdir -p -m 700 /mnt/home/${USERNAME}/.ssh")
        authorized_keys = "\n".join(cfg.system.ssh_authorized_keys)
        write_file("/mnt/home/${USERNAME}/.ssh/authorized_keys", authorized_keys)
        emit("chmod 600 /mnt/home/${USERNAME}/.ssh/authorized_keys")
        chroot("chown", "-R", "${USERNAME}:${USERNAME}",
               "/home/${USERNAME}/.ssh")
        if cfg.system.ssh == SshPolicy.ENABLE_KEYS_ONLY:
            shell("sed -i 's/^#\\?PasswordAuthentication.*/PasswordAuthentication no/' "
                  "/mnt/etc/ssh/sshd_config")

    # --- Unmount ---
    heading("Unmounting and finishing")
    cmd("umount", "-R", "/mnt")
    cmd("swapoff", "-a")
    cmd("vgchange", "-an", "lvmSystem")
    cmd("cryptsetup", "luksClose", "lvm-system")
    cmd("sync")
    emit()
    emit('echo ""')
    emit('echo "Installation complete. You may now reboot."')

    return "\n".join(lines) + "\n"
